-- migrate_v4: payment gateway support
ALTER TABLE payment MODIFY COLUMN method ENUM('BANK','MOMO','ZALOPAY','VNPAY','VIETQR') NOT NULL DEFAULT 'BANK';
ALTER TABLE payment MODIFY COLUMN status ENUM('PENDING','SUCCESS','FAILED','COMPLETED') NOT NULL DEFAULT 'PENDING';
ALTER TABLE booking ADD COLUMN payment_ref VARCHAR(80) NULL DEFAULT NULL AFTER status;
